BEGIN;
--
-- Remove field product from order
--
SET CONSTRAINTS "orders_order_product_id_096244de_fk_Products_app_product_id" IMMEDIATE; ALTER TABLE "orders_order" DROP CONSTRAINT "orders_order_product_id_096244de_fk_Products_app_product_id";
ALTER TABLE "orders_order" DROP COLUMN "product_id" CASCADE;
--
-- Create model OrderItem
--
CREATE TABLE "orders_orderitem" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "quantity" integer NOT NULL CHECK ("quantity" >= 0), "price" numeric(10, 2) NOT NULL, "order_id" varchar(20) NOT NULL, "product_id" bigint NULL);
ALTER TABLE "orders_orderitem" ADD CONSTRAINT "orders_orderitem_order_id_fe61a34d_fk_orders_order_id" FOREIGN KEY ("order_id") REFERENCES "orders_order" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orders_orderitem" ADD CONSTRAINT "orders_orderitem_product_id_afe4254a_fk_Products_app_product_id" FOREIGN KEY ("product_id") REFERENCES "Products_app_product" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "orders_orderitem_order_id_fe61a34d" ON "orders_orderitem" ("order_id");
CREATE INDEX "orders_orderitem_order_id_fe61a34d_like" ON "orders_orderitem" ("order_id" varchar_pattern_ops);
CREATE INDEX "orders_orderitem_product_id_afe4254a" ON "orders_orderitem" ("product_id");
COMMIT;
